import '../styles/globals.css'
import Head from 'next/head'
import { SessionProvider } from "next-auth/react"


export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Xl returns</title>
        <meta name="description" content="Generated by create next app" /> 
        <link rel="icon" href='/icon.png' type="image/x-icon" />
      </Head>
      <Component {...pageProps} />
    </SessionProvider>
  )
}

       
    


